#端口配置
server:
  port: 80
#数据源配置
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.93.194.195:3306/SpringBootDB
    username: xiaobai
    password: 781706889
    type: org.apache.commons.dbcp2.BasicDataSource
    dbcp2:
      #初始连接数
      initial-size: 0
      #最大连接数
      max-total: 20
      #最小空闲连接
      min-idle: 1
      #最大空闲连接
      max-idle: 20
      #超时时间
      max-wait-millis: 60000
#Mybatis配置
mybatis:
  #dao接口所在的包
  type-aliases-package: com.xiaobai.springbootdemo.dao
  #mapper映射文件接口所在的包
  mapper-locations: classpath:mapper/*.xml
